### ISSUE TITLE
JSMin causing extremely high execution times

### ISSUE THREAD

**Issue by jaimz22** [mothership-ec/mothership-install#10]
so, I got everything working and the first thing I notice is the extremely high load times. I'm talking 6 - 12 seconds to load the pricing page for a product.

I decided to profile the page and I found that there is on average 8 seconds used by JSMin, this seems to happen on every page load.

![image](https://cloud.githubusercontent.com/assets/5921193/6449618/215477d0-c0f0-11e4-9387-2d54813be6d9.png)

![image](https://cloud.githubusercontent.com/assets/5921193/6449663/5b5b0da4-c0f0-11e4-80ee-f07916da22d0.png)

The little stats boxes on the lower right however show that the page was rendered in 883ms using only 9.25 mb of ram. That might be right for the time that cog was running the process or whatever, but for the over all request I'm looking at just over 20sec of CPU time, and almost 450mb of ram usage.

I should point out that this is being run on a server with dual quad core Xeon processors @3.16GHz with 36GB of ram, and 15,000 RPM hard drives that is currently running nothing else. 

mysql is running on the same server, and this is running on PHP 5.6 (fpm)

**Comment by kuiche** [comment]
Hi, this is actually a problem we have recently noticed and are currently working on. I believe *everything* is re-minified on page load when you are in a development environment (which is the environment cog defaults to) so javascript changes are instantly visible.

This definitely needs to be fixed and we are looking into alternative ways to build assets (grunt tasks etc). There is currently a PR in cog to allow the disabling of automatic asset generation here: https://github.com/mothership-ec/cog/pull/414 but it needs a couple of tweaks before release.

NB: this isn't an issue in production environments.

**Comment by jaimz22** [comment]
would it be better if I were to put my issues into a different project, like Cog, since I've gotten through the install... I didn't even realize this was just the install repo :(

**Comment by kuiche** [comment]
Cog is better suited for this issue (and most issues relating to the core of the platform - performance, file loading etc). We don't currently have a generic "mothership repo" quite yet - this and https://github.com/mothership-ec/mothership-skeleton-theme are probably the closest to that, so general issues as well as issues which you aren't sure of their origin are *probably* OK to raise here (thoughts @thomasjthomasj?).

However, if you can get a good idea of where an issue is coming from it would be helpful for us to have the issue in the most relevant module.
