### ISSUE TITLE
Composer self-up should break more gracefully

### ISSUE THREAD

**Issue by kuiche** [mothership-ec/mothership-install#11]
Composer's self-up is run for reasons when the installer is run though it's not too important that this works, so long as the version of composer doesn't still have *that* bug.

We should probably make this look less scary if possible:
![screen shot 2015-03-03 at 16 16 01](https://cloud.githubusercontent.com/assets/5089510/6466612/da496d6a-c1c0-11e4-94b5-47eced715750.png)

**Comment by thomasjthomasj** [comment]
Will be closed when https://github.com/mothership-ec/mothership-install/pull/18 gets merged
