### ISSUE TITLE
Installer keeps on running even if Mothership throws an exception

### ISSUE THREAD

**Issue by thomasjthomasj** [mothership-ec/mothership-install#4]
There is an issue where if the Mothership installation throws an exception during the set-up process, it will keep on running. Presumably the reason for this is that the exception is caught within Mothership's codebase itself, and handled there without ever bubbling up to the installer level. A good example of this is if the user enters their database details incorrectly, the migrations will fail to run but the installation will still carry on

**Comment by kuiche** [comment]
The exception won't ever bubble up to the installer as we are running them with shell commands. You'll have to look at process exit codes (if cog actually uses them) with `proc_get_status` or similar.
