### ISSUE TITLE
Installer runs out of memory

### ISSUE THREAD

**Issue by jaimz22** [mothership-ec/mothership-install#6]
not much to say... here's the log:

http://pastebin.com/0TggUHFp

**Comment by thomasjthomasj** [comment]
Hi @jaimz22 

Did the installer complete, despite this error? If so, I believe that the command that ran out of memory is one that can be run manually within the install itself. There are two commands in Mothership which build the public view files and handle the minification of the CSS and JavaScript.

If you go to your installation directory and the following two commands:

+ `bin/cog asset:generate`
+ `bin/cog asset:dump`

This should complete the install. If not, you may need to up your memory limit in the php.ini to 256M

**Comment by jaimz22** [comment]
Yeah I'm pretty sure it did complete.

**Comment by thomasjthomasj** [comment]
Resolved by https://github.com/mothership-ec/cog/pull/432
