### ISSUE TITLE
Creating New Product. Maximum function nesting level of "100" reached, aborting!

### ISSUE THREAD

**Issue by jaimz22** [mothership-ec/mothership-install#9]
I got everything installed.

I first went to create a new product and I was presented with a 500 return from the ajax call to /admin/product/create

I took a look in the console at the return, which contained a Whoops exception. the error info is:

```
/var/www/mothership/mothership/tmp/6f/2e/ab6ee43ab413491f7fda9f36a94e.php line 1438
```

```php
 // line 399
    public function block_form_rows($context, array $blocks = array())
    {
        // line 400
        echo "\t";
        ob_start();
        // line 401
        echo "\t\t";
        $context['_parent'] = (array) $context;
        $context['_seq'] = twig_ensure_traversable((isset($context["form"]) ? $context["form"] : null));
        foreach ($context['_seq'] as $context["_key"] => $context["child"]) {
            // line 402
            echo "\t\t\t";
            echo $this->env->getExtension('form')->renderer->searchAndRenderBlock((isset($context["child"]) ? $context["child"] : null), 'row');
            echo "
\t\t";
        }
        $_parent = $context['_parent'];
        unset($context['_seq'], $context['_iterated'], $context['_key'], $context['child'], $context['_parent'], $context['loop']);
        $context = array_intersect_key($context, $_parent) + $_parent;
        // line 404
        echo "\t";
        echo trim(preg_replace('/>\s+</', '><', ob_get_clean()));
    }
```

line 1438 is 
```php
$context = array_intersect_key($context, $_parent) + $_parent;
```

**Comment by kuiche** [comment]
This *looks* like something broke in generating temp files. Possibly related to the `asset:generate` breaking earlier. Think I've had something similar once before. My suggestion would be to try `rm -rf tmp/*` and give product creation another shot.

Also did you manage to run `bin/cog asset:generate` outside of the installer without it breaking?

**Comment by kuiche** [comment]
Looking again at the actual error - you have maximum function nesting level of 100. I believe we have ours a fair bit higher, so you might actually just need to up the nesting level in your php.ini file. It doesn't sound too unlikely that it would do over 100 nested calls.

**Comment by jaimz22** [comment]
> Also did you manage to run bin/cog asset:generate outside of the installer without it breaking?

yes I did.

I'll increase my nesting. and give it a shot

**Comment by jaimz22** [comment]
increasing the max_nesting_level to 200 did fix the issue

**Comment by thomasjthomasj** [comment]
I'm going to re-open this level in Cog. I think it's an issue with Twig but I don't know if it has been resolved in a more recent version

**Comment by thomasjthomasj** [comment]
https://github.com/mothership-ec/cog/issues/421
